version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 850995549173.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Building Docker image...
      - docker build -t my-app .
      - docker tag my-app:latest 850995549173.dkr.ecr.us-east-1.amazonaws.com/my-app:latest
  post_build:
    commands:
      - echo Pushing Docker image...
      - docker push 850995549173.dkr.ecr.us-east-1.amazonaws.com/my-app:latest
      - echo Writing image definition file...
      - printf '[{"name":"my-app","imageUri":"850995549173.dkr.ecr.us-east-1.amazonaws.com/my-app:latest"}]' > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
